---
title: "CANDY demo using CANDOR"
author: "Zhenchao, Shashanka, & Nilam"
date: "2026-02-16"
output: 
  rmdformats::robobook:
    toc_depth: 3
    gallery: TRUE
    lightbox: TRUE
editor_options: 
  chunk_output_type: console
---

```{=html}
<style type="text/css">
  body, html{
    font-family: Helvetica;
}
.book .book-body .page-inner section.normal h1{
  font-family: Source Sans Pro;
  font-weight: bold;
  color:#8c1515;
} 
.book .book-body .page-inner section.normal h2,
.book .book-body .page-inner section.normal h3, 
.book .book-body .page-inner section.normal h4{
  font-family: Source Sans Pro;
  font-weight: bold;
}

.book .book-body .page-inner section.normal table  td,
.book .book-body .page-inner section.normal pre>code.r,
.book .book-body .page-inner section.normal pre{
   font-family: Andale Mono;
}

</style>
```

# Set-Up

```{r setup, warning=F, message=F}

#Change this to your working directory
setwd("~/Desktop/CANDY")

#Load Necessary Libraries

library(psych)           # data descriptives
library(tidyverse)       # data structures & visualization
library(lme4)            # let's model
library(lmerTest)        # let's model some more
library(ggplot2)

```

## Data Import

```{r data import, warning=F, message=F}

# conversation dynamics
audiophile <- read.csv("candor_conversation_dynamics_metrics_audiophile.csv", 
                       header = TRUE)

backbiter  <- read.csv("candor_conversation_dynamics_metrics_backbiter.csv", 
                       header = TRUE)

# self-report / survey data
survey <- read.csv("merged_survey.csv",
                   header = TRUE)

```

## Data descriptives 

```{r}

vars <- c(
  "total_duration","share","tl_median","tl_cv","tl_adapt","tl_predict",
  "sr_median","sr_cv","sr_adapt","sr_predict",
  "turns_total","backchannel_n","backchannel_prop",
  "rt_median","rt_cv","rt_adapt","rt_predict"
)

desc_clean <- audiophile %>%
  select(all_of(vars)) %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  summarise(
    M = mean(value, na.rm = TRUE),
    SD = sd(value, na.rm = TRUE),
    Min = min(value, na.rm = TRUE),
    Max = max(value, na.rm = TRUE),
    .groups = "drop"
  )

desc_clean


```

## Modeling

```{r}

survey <- survey %>%
  mutate(
    change_valence = affect  - pre_affect,
    change_arousal = arousal - pre_arousal
  )

survey_audiophile <- survey %>%
  select(
    convo_id, user_id, partner_id,
    change_valence, change_arousal,
    my_extraversion, my_agreeable, my_conscientious, my_neurotic, my_open
  ) %>%
  left_join(
    audiophile %>%
      mutate(
        convo_id = conversation_id,
        user_id = speaker
      ),
    by = c("convo_id", "user_id")
  )



```

### changes in affect valence and arousal

```{r}

vars <- c(
  "total_duration","share","tl_median","tl_cv","tl_adapt","tl_predict",
  "sr_median","sr_cv","sr_adapt","sr_predict",
  "turns_total","backchannel_n","backchannel_prop",
  "rt_median","rt_cv","rt_adapt","rt_predict"
)

partner_vars <- paste0("partner_", vars)

apim_df <- survey_audiophile %>%
  group_by(convo_id) %>%
  mutate(across(all_of(vars),
                ~ .[match(user_id, partner_id)],
                .names = "partner_{.col}")) %>%
  ungroup() %>%
  mutate(across(all_of(c(vars, partner_vars)),
                ~ as.numeric(scale(.)),
                .names = "{.col}_z"))

model_valence <- lmer(
  change_valence ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

model_arousal <- lmer(
    change_arousal ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

summary(model_arousal)
summary(model_valence)

```

### personality

```{r}

model_extravert <- lmer(
  my_extraversion ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

model_agree <- lmer(
    my_agreeable ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

model_consci <- lmer(
    my_conscientious ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

model_neuro <- lmer(
    my_neurotic ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

model_open <- lmer(
    my_open ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z +
    (1 | convo_id),
  data = apim_df,
  REML = FALSE
)

summary(model_extravert)
summary(model_agree)
summary(model_consci)
summary(model_neuro)
summary(model_open)

```

### personality no random effects

```{r}

model_extravert <- lm(
  my_extraversion ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z,
  data = apim_df
)

model_agree <- lm(
    my_agreeable ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z,
  data = apim_df
)

model_consci <- lm(
    my_conscientious ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z,
  data = apim_df
)

model_neuro <- lm(
    my_neurotic ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z,
  data = apim_df
)

model_open <- lm(
    my_open ~
    share_z + #partner_share_z +
    tl_median_z + partner_tl_median_z +
    tl_cv_z + partner_tl_cv_z +
    tl_adapt_z + partner_tl_adapt_z +
    tl_predict_z + partner_tl_predict_z +
    sr_median_z + partner_sr_median_z +
    sr_cv_z + partner_sr_cv_z +
    sr_adapt_z + partner_sr_adapt_z +
    sr_predict_z + partner_sr_predict_z +
    turns_total_z + partner_turns_total_z +
    backchannel_n_z + partner_backchannel_n_z +
    backchannel_prop_z + partner_backchannel_prop_z +
    rt_median_z + partner_rt_median_z +
    rt_cv_z + partner_rt_cv_z +
    rt_adapt_z + partner_rt_adapt_z +
    rt_predict_z + partner_rt_predict_z,
  data = apim_df
)

summary(model_extravert)
summary(model_agree)
summary(model_consci)
summary(model_neuro)
summary(model_open)

```

### visualization 

#### palettes and lables

```{r}

library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(forcats)
library(ggplot2)
library(broom.mixed)
library(lme4)
library(scales)

# Nice qualitative palette for dimensions
pal_dim <- c(
  "Speaking time / volume" = "#009E73",  # green
  "Turn length"            = "#CC79A7",  # purple-pink
  "Speech rate"            = "#0072B2",  # blue
  "Backchannels"           = "#E69F00",  # orange
  "Response time"          = "#D55E00"   # vermillion
)

metric_labels <- c(
  share_z = "Speaking share",
  tl_median_z = "Turn length: median",
  tl_cv_z = "Turn length: CV",
  tl_adapt_z = "Turn length: adaptability",
  tl_predict_z = "Turn length: predictability",
  sr_median_z = "Speech rate: median",
  sr_cv_z = "Speech rate: CV",
  sr_adapt_z = "Speech rate: adaptability",
  sr_predict_z = "Speech rate: predictability",
  turns_total_z = "Turn count",
  backchannel_n_z = "Backchannels: count",
  backchannel_prop_z = "Backchannels: proportion",
  rt_median_z = "Response time: median",
  rt_cv_z = "Response time: CV",
  rt_adapt_z = "Response time: adaptability",
  rt_predict_z = "Response time: predictability",

  partner_tl_median_z = "Partner turn length: median",
  partner_tl_cv_z = "Partner turn length: CV",
  partner_tl_adapt_z = "Partner turn length: adaptability",
  partner_tl_predict_z = "Partner turn length: predictability",
  partner_sr_median_z = "Partner speech rate: median",
  partner_sr_cv_z = "Partner speech rate: CV",
  partner_sr_adapt_z = "Partner speech rate: adaptability",
  partner_sr_predict_z = "Partner speech rate: predictability",
  partner_turns_total_z = "Partner turn count",
  partner_backchannel_n_z = "Partner backchannels: count",
  partner_backchannel_prop_z = "Partner backchannels: proportion",
  partner_rt_median_z = "Partner response time: median",
  partner_rt_cv_z = "Partner response time: CV",
  partner_rt_adapt_z = "Partner response time: adaptability",
  partner_rt_predict_z = "Partner response time: predictability"
)

model_predictors <- c(
  "share_z",
  "tl_median_z", "partner_tl_median_z",
  "tl_cv_z", "partner_tl_cv_z",
  "tl_adapt_z", "partner_tl_adapt_z",
  "tl_predict_z", "partner_tl_predict_z",
  "sr_median_z", "partner_sr_median_z",
  "sr_cv_z", "partner_sr_cv_z",
  "sr_adapt_z", "partner_sr_adapt_z",
  "sr_predict_z", "partner_sr_predict_z",
  "turns_total_z", "partner_turns_total_z",
  "backchannel_n_z", "partner_backchannel_n_z",
  "backchannel_prop_z", "partner_backchannel_prop_z",
  "rt_median_z", "partner_rt_median_z",
  "rt_cv_z", "partner_rt_cv_z",
  "rt_adapt_z", "partner_rt_adapt_z",
  "rt_predict_z", "partner_rt_predict_z"
)

metric_dimension <- tibble(
  term = model_predictors,
  metric_label = recode(term, !!!metric_labels),
  dimension = case_when(
    str_detect(term, "share|turns_total") ~ "Speaking time / volume",
    str_detect(term, "tl_") ~ "Turn length",
    str_detect(term, "sr_") ~ "Speech rate",
    str_detect(term, "backchannel") ~ "Backchannels",
    str_detect(term, "rt_") ~ "Response time",
    TRUE ~ "Other"
  ),
  role = if_else(str_detect(term, "^partner_"), "Partner", "Self"),
  label = paste0(metric_label, if_else(role == "Partner", " (Partner)", " (Self)"))
)

```


#### color key 

```{r}

library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)

pal_dim <- c(
  "Speaking time / volume" = "#009E73",  # green
  "Turn length"            = "#CC79A7",  # purple-pink
  "Speech rate"            = "#0072B2",  # blue
  "Backchannels"           = "#E69F00",  # orange
  "Response time"          = "#D55E00"   # vermillion
)

dimension_key <- tibble(
  dimension = names(pal_dim),
  short_description = c(
    "How much each person speaks",
    "How speakers structure turns",
    "How quickly speakers talk",
    "Short listener responses",
    "How quickly speakers reply"
  ),
  examples = c(
    "Speaking share, turn count",
    "Median turn length, CV, adaptability",
    "Median WPM, CV, adaptability",
    "Backchannel count/proportion",
    "Median response time, CV, adaptability"
  )
) %>%
  mutate(
    dimension = factor(dimension, levels = names(pal_dim)),
    y = rev(row_number())
  )

p_dimension_key <- ggplot(dimension_key, aes(y = y)) +
  geom_tile(
    aes(x = 0, fill = dimension),
    width = 0.45,
    height = 0.70,
    color = "white",
    linewidth = 1
  ) +
  geom_text(
    aes(x = 0.45, label = dimension, color = dimension),
    hjust = 0,
    fontface = "bold",
    size = 5.6
  ) +
  geom_text(
    aes(x = 3.4, label = short_description),
    hjust = 0,
    size = 4.5,
    color = "gray20"
  ) +
  geom_text(
    aes(x = 6.5, label = examples),
    hjust = 0,
    size = 4.1,
    color = "gray35"
  ) +
  scale_fill_manual(values = pal_dim) +
  scale_color_manual(values = pal_dim) +
  coord_cartesian(xlim = c(-0.35, 10.5), ylim = c(0.4, 5.7), clip = "off") +
  labs(
    title = "Color Key: Dimensions of Conversation Dynamics",
    subtitle = "The same colors are used across descriptive, personality, and affect plots"
  ) +
  theme_void(base_size = 14) +
  theme(
    plot.title = element_text(face = "bold", size = 20, margin = margin(b = 6)),
    plot.subtitle = element_text(size = 13, color = "gray35", margin = margin(b = 14)),
    legend.position = "none",
    plot.margin = margin(20, 35, 20, 35)
  )

p_dimension_key

ggsave(
  "conversation_dynamics_color_key.png",
  p_dimension_key,
  width = 12,
  height = 4.5,
  dpi = 300,
  bg = "white"
)

```

#### personality traits * 5 

```{r}

apim_df_big5_z <- apim_df %>%
  mutate(
    extraversion_z     = as.numeric(scale(my_extraversion)),
    agreeable_z        = as.numeric(scale(my_agreeable)),
    conscientious_z    = as.numeric(scale(my_conscientious)),
    neurotic_z         = as.numeric(scale(my_neurotic)),
    open_z             = as.numeric(scale(my_open))
  )

pred_formula <- paste(model_predictors, collapse = " + ")

fit_big5_z <- function(outcome) {
  lmer(
    as.formula(paste0(outcome, " ~ ", pred_formula, " + (1 | convo_id)")),
    data = apim_df_big5_z,
    REML = FALSE
  )
}

big5_models_z <- list(
  Extraversion      = fit_big5_z("extraversion_z"),
  Agreeableness     = fit_big5_z("agreeable_z"),
  Conscientiousness = fit_big5_z("conscientious_z"),
  Neuroticism       = fit_big5_z("neurotic_z"),
  Openness          = fit_big5_z("open_z")
)

big5_coef_z <- imap_dfr(big5_models_z, function(mod, nm) {
  broom.mixed::tidy(mod, effects = "fixed", conf.int = TRUE) %>%
    filter(term %in% model_predictors) %>%
    mutate(outcome = nm)
}) %>%
  left_join(metric_dimension, by = "term") %>%
  mutate(
    sig = case_when(
      p.value < .001 ~ "***",
      p.value < .01  ~ "**",
      p.value < .05  ~ "*",
      p.value < .10  ~ "+",
      TRUE ~ ""
    ),
    significant = p.value < .05,
    outcome = factor(
      outcome,
      levels = c("Extraversion", "Agreeableness", "Conscientiousness", "Neuroticism", "Openness")
    )
  )

plot_big5_trait <- function(trait_name, sig_only = FALSE) {

  dat <- big5_coef_z %>%
    filter(outcome == trait_name)

  if (sig_only) {
    dat <- dat %>% filter(p.value < .05)
  }

  dat <- dat %>%
    mutate(
      label = fct_reorder(label, estimate)
    )

  ggplot(dat, aes(x = estimate, y = label, color = dimension)) +
    geom_vline(xintercept = 0, color = "gray40", linewidth = 0.5) +
    geom_errorbarh(
      aes(xmin = conf.low, xmax = conf.high),
      height = 0.18,
      linewidth = 0.8,
      alpha = ifelse(dat$p.value < .05, 1, 0.35)
    ) +
    geom_point(
      aes(alpha = significant),
      size = 3
    ) +
    geom_text(
      aes(label = sig),
      nudge_x = 0.03,
      size = 4,
      color = "black",
      show.legend = FALSE
    ) +
    scale_color_manual(values = pal_dim) +
    scale_alpha_manual(values = c(`TRUE` = 1, `FALSE` = 0.35), guide = "none") +
    labs(
      title = ifelse(
        sig_only,
        paste0(trait_name, ": significant conversation-dynamic predictors"),
        paste0(trait_name, ": all conversation-dynamic predictors")
      ),
      subtitle = "Standardized estimates; predictors and outcome are z-scored",
      x = "Standardized estimate",
      y = NULL,
      color = "Dimension"
    ) +
    theme_minimal(base_size = 13) +
    theme(
      plot.title = element_text(face = "bold", size = 17),
      plot.subtitle = element_text(size = 11),
      panel.grid.minor = element_blank(),
      legend.position = "bottom"
    )
}

###### all coefficients
big5_traits <- names(big5_models_z)

plots_big5_all <- map(big5_traits, ~ plot_big5_trait(.x, sig_only = FALSE))
names(plots_big5_all) <- big5_traits

plots_big5_all$Extraversion


###### sig coefficients ONLY
plots_big5_sig <- map(big5_traits, ~ plot_big5_trait(.x, sig_only = TRUE))
names(plots_big5_sig) <- big5_traits

iwalk(plots_big5_sig, function(p, nm) {
  ggsave(
    filename = paste0("figures_big5_sig/big5_", str_to_lower(nm), "_significant_coefficients.png"),
    plot = p,
    width = 6.3,
    height = 3.7,
    dpi = 300
  )
})

plots_big5_sig$Extraversion
plots_big5_sig$Agreeableness
plots_big5_sig$Conscientiousness
plots_big5_sig$Neuroticism
plots_big5_sig$Openness

```

#### personality heatmaps

```{r}

p_big5_heatmap_tight <- big5_coef_z %>%
    mutate(
        label = fct_rev(label),
        sig_label = sig
    ) %>%
    ggplot(aes(x = outcome, y = label, fill = estimate)) +
    geom_tile(color = "white", linewidth = 0.5) +
    geom_text(aes(label = sig_label), size = 4.5, color = "black") +
    scale_fill_gradient2(
        low = "#4575B4",
        mid = "white",
        high = "#D73027",
        midpoint = 0,
        limits = c(-0.15, 0.15),
        oob = scales::squish,
        name = "Std. estimate"
    ) +
    labs(
        title = "Big Five personality traits show distinct conversation-dynamic profiles",
        subtitle = "Color scale compressed to show small standardized effects; stars indicate significance",
        x = NULL,
        y = NULL
    ) +
    theme_minimal(base_size = 13) +
    theme(
        plot.title = element_text(face = "bold", size = 17),
        plot.subtitle = element_text(size = 11),
        axis.text.x = element_text(face = "bold"),
        panel.grid = element_blank(),
        legend.position = "right"
    )

p_big5_heatmap_tight

p_big5_heatmap_sig <- big5_coef_z %>%
    mutate(
        estimate_plot = if_else(p.value < .05, estimate, NA_real_),
        label = fct_rev(label),
        sig_label = if_else(p.value < .05, sig, "")
    ) %>%
    ggplot(aes(x = outcome, y = label, fill = estimate_plot)) +
    geom_tile(color = "white", linewidth = 0.5) +
    geom_text(aes(label = sig_label), size = 4.5, color = "black") +
    scale_fill_gradient2(
        low = "#4575B4",
        mid = "white",
        high = "#D73027",
        midpoint = 0,
        limits = c(-0.15, 0.15),
        oob = scales::squish,
        na.value = "gray95",
        name = "Std. estimate"
    ) +
    labs(
        title = "Significant Big Five associations with conversation dynamics",
        subtitle = "Gray cells are non-significant; stars indicate p-values",
        x = NULL,
        y = NULL
    ) +
    theme_minimal(base_size = 13) +
    theme(
        plot.title = element_text(face = "bold", size = 17),
        plot.subtitle = element_text(size = 11),
        axis.text.x = element_text(face = "bold"),
        panel.grid = element_blank(),
        legend.position = "right"
    )

p_big5_heatmap_sig



```


#### affect

```{r}

# ============================================================
# Affect plots for presentation:
# - raw x-axis
# - term-specific central display range (default 1st-99th percentile)
# - raw points + raw dashed line
# - model-adjusted solid line + CI ribbon
# - separate plots for Δ Valence and Δ Arousal
# ============================================================

suppressPackageStartupMessages({
    library(dplyr)
    library(tidyr)
    library(purrr)
    library(stringr)
    library(ggplot2)
    library(broom.mixed)
    library(lme4)
    library(tibble)
})

# ---------------------------
# 1. Settings you can change
# ---------------------------
display_q <- c(0.01, 0.99)   # use central 1%-99% for each metric in the DISPLAY
n_pred_points <- 150         # smoothness of adjusted line
point_alpha <- 0.12
point_size <- 0.9
ribbon_alpha <- 0.18
jitter_height <- 0.05        # small vertical jitter helps with discrete affect values
use_jitter <- TRUE           # set FALSE if you want plain points

# ---------------------------
# 2. Palette for dimensions
# ---------------------------
pal_dim <- c(
    "Speaking time / volume" = "#009E73",  # green
    "Turn length"            = "#CC79A7",  # magenta
    "Speech rate"            = "#0072B2",  # blue
    "Backchannels"           = "#E69F00",  # orange
    "Response time"          = "#D55E00"   # vermillion
)

# ---------------------------
# 3. Predictor labels
# ---------------------------
metric_labels <- c(
    share_z = "Speaking share",
    tl_median_z = "Turn length: median",
    tl_cv_z = "Turn length: CV",
    tl_adapt_z = "Turn length: adaptability",
    tl_predict_z = "Turn length: predictability",
    sr_median_z = "Speech rate: median",
    sr_cv_z = "Speech rate: CV",
    sr_adapt_z = "Speech rate: adaptability",
    sr_predict_z = "Speech rate: predictability",
    turns_total_z = "Turn count",
    backchannel_n_z = "Backchannels: count",
    backchannel_prop_z = "Backchannels: proportion",
    rt_median_z = "Response time: median",
    rt_cv_z = "Response time: CV",
    rt_adapt_z = "Response time: adaptability",
    rt_predict_z = "Response time: predictability",
    
    partner_tl_median_z = "Partner turn length: median",
    partner_tl_cv_z = "Partner turn length: CV",
    partner_tl_adapt_z = "Partner turn length: adaptability",
    partner_tl_predict_z = "Partner turn length: predictability",
    partner_sr_median_z = "Partner speech rate: median",
    partner_sr_cv_z = "Partner speech rate: CV",
    partner_sr_adapt_z = "Partner speech rate: adaptability",
    partner_sr_predict_z = "Partner speech rate: predictability",
    partner_turns_total_z = "Partner turn count",
    partner_backchannel_n_z = "Partner backchannels: count",
    partner_backchannel_prop_z = "Partner backchannels: proportion",
    partner_rt_median_z = "Partner response time: median",
    partner_rt_cv_z = "Partner response time: CV",
    partner_rt_adapt_z = "Partner response time: adaptability",
    partner_rt_predict_z = "Partner response time: predictability"
)

model_predictors <- c(
    "share_z",
    "tl_median_z", "partner_tl_median_z",
    "tl_cv_z", "partner_tl_cv_z",
    "tl_adapt_z", "partner_tl_adapt_z",
    "tl_predict_z", "partner_tl_predict_z",
    "sr_median_z", "partner_sr_median_z",
    "sr_cv_z", "partner_sr_cv_z",
    "sr_adapt_z", "partner_sr_adapt_z",
    "sr_predict_z", "partner_sr_predict_z",
    "turns_total_z", "partner_turns_total_z",
    "backchannel_n_z", "partner_backchannel_n_z",
    "backchannel_prop_z", "partner_backchannel_prop_z",
    "rt_median_z", "partner_rt_median_z",
    "rt_cv_z", "partner_rt_cv_z",
    "rt_adapt_z", "partner_rt_adapt_z",
    "rt_predict_z", "partner_rt_predict_z"
)

metric_dimension <- tibble(
    term = model_predictors,
    metric_label = recode(term, !!!metric_labels),
    dimension = case_when(
        str_detect(term, "share|turns_total") ~ "Speaking time / volume",
        str_detect(term, "tl_") ~ "Turn length",
        str_detect(term, "sr_") ~ "Speech rate",
        str_detect(term, "backchannel") ~ "Backchannels",
        str_detect(term, "rt_") ~ "Response time",
        TRUE ~ "Other"
    ),
    role = if_else(str_detect(term, "^partner_"), "Partner", "Self"),
    label = paste0(metric_label, if_else(role == "Partner", " (Partner)", " (Self)"))
)

# ---------------------------
# 4. Affect models
#    Assumes you already fit:
#    model_valence and model_arousal
#    and have apim_df with raw variables + change_valence/change_arousal
# ---------------------------
affect_models <- list(
    `Δ Valence` = model_valence,
    `Δ Arousal` = model_arousal
)

# ---------------------------
# 5. Significant predictors only
# ---------------------------
affect_sig_terms <- imap_dfr(affect_models, function(mod, nm) {
    broom.mixed::tidy(mod, effects = "fixed", conf.int = TRUE) %>%
        filter(term %in% model_predictors) %>%
        filter(p.value < .05) %>%
        mutate(outcome = nm)
}) %>%
    left_join(metric_dimension, by = "term") %>%
    mutate(
        raw_term = str_remove(term, "_z$"),
        outcome_var = if_else(outcome == "Δ Valence", "change_valence", "change_arousal"),
        sig = case_when(
            p.value < .001 ~ "***",
            p.value < .01  ~ "**",
            p.value < .05  ~ "*",
            TRUE ~ ""
        )
    ) %>%
    arrange(outcome, p.value)

# ---------------------------
# 6. Helper: raw data for each significant effect
# ---------------------------
make_affect_raw_data <- function(outcome, term, raw_term, metric_label, dimension, role, label,
                                 estimate, std.error, statistic, p.value, conf.low, conf.high,
                                 outcome_var, sig) {
    
    tmp <- apim_df %>%
        select(convo_id, user_id, all_of(outcome_var), all_of(raw_term)) %>%
        rename(
            y_value = all_of(outcome_var),
            x_value = all_of(raw_term)
        ) %>%
        filter(is.finite(x_value), is.finite(y_value))
    
    # term-specific display range
    x_low  <- quantile(tmp$x_value, display_q[1], na.rm = TRUE)
    x_high <- quantile(tmp$x_value, display_q[2], na.rm = TRUE)
    
    tmp %>%
        mutate(
            outcome = outcome,
            term = term,
            raw_term = raw_term,
            dimension = dimension,
            label = label,
            x_low = x_low,
            x_high = x_high
        ) %>%
        filter(x_value >= x_low, x_value <= x_high)
}

affect_raw_plot_dat <- pmap_dfr(
    affect_sig_terms %>%
        select(
            outcome, term, raw_term, metric_label, dimension, role, label,
            estimate, std.error, statistic, p.value, conf.low, conf.high,
            outcome_var, sig
        ),
    make_affect_raw_data
)

# ---------------------------
# 7. Helper: model-adjusted predictions + CIs
#    using fixed-effect VCOV
# ---------------------------
make_adjusted_prediction_ci <- function(model, term, raw_term, label, outcome, dimension,
                                        data = apim_df, q = display_q, n_points = n_pred_points) {
    
    # display/prediction range = central quantile range for this raw metric
    x_low  <- quantile(data[[raw_term]], q[1], na.rm = TRUE)
    x_high <- quantile(data[[raw_term]], q[2], na.rm = TRUE)
    
    x_seq <- seq(x_low, x_high, length.out = n_points)
    
    raw_mean <- mean(data[[raw_term]], na.rm = TRUE)
    raw_sd   <- sd(data[[raw_term]], na.rm = TRUE)
    
    # build newdata with all predictors held at 0
    newdat <- as.data.frame(matrix(0, nrow = length(x_seq), ncol = length(model_predictors)))
    names(newdat) <- model_predictors
    
    # convert displayed raw x-values into z-values used in the fitted model
    newdat[[term]] <- (x_seq - raw_mean) / raw_sd
    
    # add grouping variable for lmer
    newdat$convo_id <- data$convo_id[which(!is.na(data$convo_id))[1]]
    
    # fixed-effects prediction + CI
    X <- model.matrix(delete.response(terms(model)), newdat)
    beta <- fixef(model)
    V <- vcov(model)
    
    fit <- as.numeric(X %*% beta)
    se  <- sqrt(diag(X %*% V %*% t(X)))
    
    tibble(
        x_value = x_seq,
        predicted = fit,
        conf.low = fit - 1.96 * se,
        conf.high = fit + 1.96 * se,
        term = term,
        raw_term = raw_term,
        label = label,
        outcome = outcome,
        dimension = dimension
    )
}

affect_pred_ci_dat <- pmap_dfr(
    affect_sig_terms %>%
        mutate(model = map(outcome, ~ affect_models[[.x]])) %>%
        select(model, term, raw_term, label, outcome, dimension),
    make_adjusted_prediction_ci,
    data = apim_df,
    q = display_q,
    n_points = n_pred_points
)

# ---------------------------
# 8. Plotting function
# ---------------------------
plot_affect_outcome <- function(outcome_name) {
    
    raw_dat <- affect_raw_plot_dat %>%
        filter(outcome == outcome_name)
    
    pred_dat <- affect_pred_ci_dat %>%
        filter(outcome == outcome_name)
    
    p <- ggplot() +
        # CI ribbon
        geom_ribbon(
            data = pred_dat,
            aes(x = x_value, ymin = conf.low, ymax = conf.high, fill = dimension),
            alpha = ribbon_alpha,
            color = NA
        )
    
    # raw points
    if (use_jitter) {
        p <- p + geom_jitter(
            data = raw_dat,
            aes(x = x_value, y = y_value, color = "gray"),
            alpha = point_alpha,
            size = point_size,
            width = 0,
            height = jitter_height
        )
    } else {
        p <- p + geom_point(
            data = raw_dat,
            aes(x = x_value, y = y_value, color = "gray"),
            alpha = point_alpha,
            size = point_size
        )
    }
    
    p +
        # raw dashed line
        #geom_smooth(
        #    data = raw_dat,
        #    aes(x = x_value, y = y_value, color = dimension),
        #    method = "lm",
        #    se = FALSE,
        #    linewidth = 0.8,
        #    linetype = "dashed"
        #) +
        # adjusted line
        geom_line(
            data = pred_dat,
            aes(x = x_value, y = predicted, color = dimension),
            linewidth = 1.5
        ) +
        facet_wrap(~ label, scales = "free_x", ncol = 2) +
        scale_color_manual(values = pal_dim) +
        scale_fill_manual(values = pal_dim) +
        labs(
            title = paste0("Conversation dynamics associated with ", outcome_name),
            subtitle = paste0(
                "Display range uses the central ",
                round(display_q[1] * 100), "–", round(display_q[2] * 100),
                "th percentiles of each conversation dynamic; ",
                "dashed lines = raw associations, solid lines/ribbons = model-adjusted associations"
            ),
            x = "Conversation dynamic, raw scale",
            y = outcome_name,
            color = "Dimension",
            fill = "Dimension"
        ) +
        theme_minimal(base_size = 14) +
        theme(
            plot.title = element_text(face = "bold", size = 18),
            plot.subtitle = element_text(size = 11, color = "gray30"),
            strip.text = element_text(face = "bold", size = 12),
            panel.grid.minor = element_blank(),
            legend.position = "bottom"
        )
}

# ---------------------------
# 9. Create plots
# ---------------------------
p_valence <- plot_affect_outcome("Δ Valence")
p_arousal <- plot_affect_outcome("Δ Arousal")

p_valence
p_arousal


```





